title: Coding to Mastery
author: sydalwedaie
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  A blog, documenting my journey in taking my basic coding slikls all the way to job-ready level.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima 
